name: prototipo_app_uncisal
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # cupertino_icons: ^1.0.0

  get: ^3.15.0
  audioplayers: ^0.16.2
  file_picker: ^2.0.11
  http: ^0.12.2


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

#  uses-material-designe: true
  assets:
    - assets/images/logo/Pygus.jpg
    - assets/images/logo/pygus-logo.png
    - assets/images/words/boca.jpg
    - assets/audio/bo.mp3